# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the application files into the container
COPY GramEm.py Mapping.py ./

# Install dependencies
RUN pip install --no-cache-dir \
    flask transformers torch regex spellchecker

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["python", "GramEm.py"]
